version: 0.2

phases:
  pre_build:
    commands:
      - export GITSHA1="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - export GITHEAD="$(echo $GITSHA1 | cut -c1-7)"
      - export GITURL='git@github.com:StevenACoffman/dummy.git'
      - export USER=codebuild
      - export GITSTATUS="no changes"
      - echo "Creating scm-source.json"
      - touch scm-source.json
  build:
    commands:
      - echo Build started on `date`
      - env
      - echo "Creating scm-source.json"
      - !!string 'echo "{\"url\": \"git:$GITURL\", \"revision\": \"$GITHEAD\", \"author\": \"$USER\", \"status\": \"$GITSTATUS\"}" > scm-source.json'
      - echo Building the Docker image...
      - make all
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push artifactory.acorn.cirrostratus.org/cypress/dummy
